### ISSUE TITLE
Make changesets filenames as dates

### ISSUE THREAD

**Issue by maning** [mapbox/osm-history-processor#1]
Instead of using replication diff state filenames, lets use a more descriptive name for the team changesets files like dates `YYYY-MM-DD`.  For example, `https://someurl/2015-12-04.tar.gz`.
This reduces one more step in our [peer review process](https://github.com/mapbox/data/wiki/Data-Team-Peer-Review-Process#setup).

In addition, let's maintain an archive of previous files for say a month if ever we need to go back and put in a publicly available download URL instead of `https://s3.amazonaws.com/mapbox/osm-history-processor/`.  We can purge this directory every month.

**Comment by Rub21** [comment]
Done!
from now on we are going to get the files with date as name. example https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/2015-12-06.tar.gz
