### ISSUE TITLE
Previous week's changes as one latest.tar.gz file

### ISSUE THREAD

**Issue by maning** [mapbox/osm-history-processor#3]

**Comment by Rub21** [comment]
@maning @planemad  is this should run once per week, or every day,?  I notice sometime we need the files from a day before.   what do you thing?

**Comment by planemad** [comment]
@Rub21 Everyday will work well.

**Comment by Rub21** [comment]
This is done!!!, however is not working yet  we are waiting for https://github.com/mapbox/osm-history-processor/issues/4

**Comment by maning** [comment]
The latest.tar.gz file now includes all the changes of a user in the last 7 days.  Previously it was 1 file per user per day.  Is this the expected output now?

**Comment by planemad** [comment]
@maning @Rub21 https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/latest.tar.gz looks good. Just one more thing:
- [ ] Drop empty editions #2
