### ISSUE TITLE
Instance for  OSM-history-processor

### ISSUE THREAD

**Issue by Rub21** [mapbox/osm-history-processor#4]
osm-history-processor is a script to filter data-team edition data from `s3://osm-changesets` a save into `s3://mapbox/osm-history-processor`, 
Right now i am running the script in a production stack [osm-edit-report-service-production](https://github.com/mapbox/osm-edit-report-service). I think it is not  a good way to do that.  because if we shout down the stack or we make a deployment  the OSM-history-processor  will died,  even if we want to make  a deployment, something will wrong,  because I added S3 Bucket access to   the instance to read the S3 files. 

What should be the suggestion  for this?  this is not a big app, but i think,  it need a own ec2 to run the script. 

cc. @geohacker @aaronlidman @rclark @maning @planemad

**Comment by Rub21** [comment]
any thoughts?

**Comment by rclark** [comment]
https://github.com/mapbox/dynamosm is incredibly well suited for this, though it still needs a couple of weeks before it is stable enough to rely on. 

With Dynamosm, this project could become a simple (and cheap!) Lambda function that runs each time there's a new event in the [Changed DynamoDB features stream](https://github.com/mapbox/dynamosm/blob/master/architecture.md#understanding-the-pipeline). Each run will represent an edit to a single node, way, or relation, and will include the name of the user who made the edit. With this information, the lambda function could update the backend database, incrementing the edit count for that user.

Can you continue to use what you've got now for the next couple of weeks while Dynamosm stabilizes?

**Comment by geohacker** [comment]
> incrementing the edit count for that user.

@rclark this is more than counting the edits. osm-history-processor generates a .osm file of all the changes by our team for review, every week. You think this is a usecase for dynamosm?

**Comment by rclark** [comment]
@geohacker it definitely could do this. We should chat about it sometime so I'm sure that I understand what the parser is doing & why. 

That said, I think I misinterpreted @Rub21's question: he's more concerned about API stack stability than the parsing details. I'll look closer at that stack later today.

**Comment by geohacker** [comment]
@rclark @Rub21 - yeah, it's slightly confusing but what we want is now a separate stack for osm-history-processor. Can voice tomorrow may be.

**Comment by Rub21** [comment]
sorry, for misunderstand,  for now  I  will run the osm-history-processor in  production [instance](https://github.com/mapbox/osm-edit-report-service), perhaps  couple of weeks we are going to use a watckbot https://github.com/mapbox/peer-review/issues/9, and other ways to do the peer-review. 

no more  actions here. close here.
